[2022-04-03 23:18:52,914] {scheduler_job.py:182} INFO - Started process (PID=3574) to work on /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:18:52,915] {scheduler_job.py:633} INFO - Processing file /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py for tasks to queue
[2022-04-03 23:18:52,916] {logging_mixin.py:104} INFO - [2022-04-03 23:18:52,916] {dagbag.py:487} INFO - Filling up the DagBag from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:18:52,918] {logging_mixin.py:104} INFO - [2022-04-03 23:18:52,918] {dagbag.py:320} ERROR - Failed to import: /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/airflow/dags/subdags/subdag_paralell_dag.py", line 5
    with DAG(dag_id=f'{parent_dag_id}.{child_dag_id}', default_args) as dag:
                                                       ^
SyntaxError: positional argument follows keyword argument
[2022-04-03 23:18:52,922] {scheduler_job.py:645} WARNING - No viable dags retrieved from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:18:52,996] {scheduler_job.py:190} INFO - Processing /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py took 0.084 seconds
[2022-04-03 23:19:23,094] {scheduler_job.py:182} INFO - Started process (PID=3806) to work on /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:19:23,095] {scheduler_job.py:633} INFO - Processing file /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py for tasks to queue
[2022-04-03 23:19:23,095] {logging_mixin.py:104} INFO - [2022-04-03 23:19:23,095] {dagbag.py:487} INFO - Filling up the DagBag from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:19:23,096] {logging_mixin.py:104} INFO - [2022-04-03 23:19:23,096] {dagbag.py:320} ERROR - Failed to import: /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/airflow/dags/subdags/subdag_paralell_dag.py", line 5
    with DAG(dag_id=f'{parent_dag_id}.{child_dag_id}', default_args) as dag:
                                                       ^
SyntaxError: positional argument follows keyword argument
[2022-04-03 23:19:23,096] {scheduler_job.py:645} WARNING - No viable dags retrieved from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:19:23,163] {scheduler_job.py:190} INFO - Processing /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py took 0.071 seconds
[2022-04-03 23:19:53,277] {scheduler_job.py:182} INFO - Started process (PID=3888) to work on /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:19:53,278] {scheduler_job.py:633} INFO - Processing file /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py for tasks to queue
[2022-04-03 23:19:53,279] {logging_mixin.py:104} INFO - [2022-04-03 23:19:53,279] {dagbag.py:487} INFO - Filling up the DagBag from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:19:53,287] {logging_mixin.py:104} INFO - [2022-04-03 23:19:53,287] {dagbag.py:320} ERROR - Failed to import: /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/airflow/dags/subdags/subdag_paralell_dag.py", line 5
    with DAG(dag_id=f'{parent_dag_id}.{child_dag_id}', default_args) as dag:
                                                       ^
SyntaxError: positional argument follows keyword argument
[2022-04-03 23:19:53,287] {scheduler_job.py:645} WARNING - No viable dags retrieved from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:19:53,344] {scheduler_job.py:190} INFO - Processing /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py took 0.069 seconds
[2022-04-03 23:20:23,487] {scheduler_job.py:182} INFO - Started process (PID=3909) to work on /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:20:23,488] {scheduler_job.py:633} INFO - Processing file /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py for tasks to queue
[2022-04-03 23:20:23,488] {logging_mixin.py:104} INFO - [2022-04-03 23:20:23,488] {dagbag.py:487} INFO - Filling up the DagBag from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:20:23,490] {logging_mixin.py:104} INFO - [2022-04-03 23:20:23,489] {dagbag.py:320} ERROR - Failed to import: /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/airflow/dags/subdags/subdag_paralell_dag.py", line 5
    with DAG(dag_id=f'{parent_dag_id}.{child_dag_id}', default_args) as dag:
                                                       ^
SyntaxError: positional argument follows keyword argument
[2022-04-03 23:20:23,490] {scheduler_job.py:645} WARNING - No viable dags retrieved from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:20:23,560] {scheduler_job.py:190} INFO - Processing /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py took 0.075 seconds
[2022-04-03 23:20:53,682] {scheduler_job.py:182} INFO - Started process (PID=4019) to work on /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:20:53,683] {scheduler_job.py:633} INFO - Processing file /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py for tasks to queue
[2022-04-03 23:20:53,683] {logging_mixin.py:104} INFO - [2022-04-03 23:20:53,683] {dagbag.py:487} INFO - Filling up the DagBag from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:20:53,684] {logging_mixin.py:104} INFO - [2022-04-03 23:20:53,684] {dagbag.py:320} ERROR - Failed to import: /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/airflow/dags/subdags/subdag_paralell_dag.py", line 5
    with DAG(dag_id=f'{parent_dag_id}.{child_dag_id}', default_args) as dag:
                                                       ^
SyntaxError: positional argument follows keyword argument
[2022-04-03 23:20:53,685] {scheduler_job.py:645} WARNING - No viable dags retrieved from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:20:53,713] {scheduler_job.py:190} INFO - Processing /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py took 0.033 seconds
[2022-04-03 23:21:23,840] {scheduler_job.py:182} INFO - Started process (PID=4159) to work on /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:21:23,841] {scheduler_job.py:633} INFO - Processing file /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py for tasks to queue
[2022-04-03 23:21:23,841] {logging_mixin.py:104} INFO - [2022-04-03 23:21:23,841] {dagbag.py:487} INFO - Filling up the DagBag from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:21:23,843] {logging_mixin.py:104} INFO - [2022-04-03 23:21:23,842] {dagbag.py:320} ERROR - Failed to import: /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/airflow/dags/subdags/subdag_paralell_dag.py", line 5
    with DAG(dag_id=f'{parent_dag_id}.{child_dag_id}', default_args) as dag:
                                                       ^
SyntaxError: positional argument follows keyword argument
[2022-04-03 23:21:23,843] {scheduler_job.py:645} WARNING - No viable dags retrieved from /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py
[2022-04-03 23:21:23,873] {scheduler_job.py:190} INFO - Processing /home/airflow/airflow/dags/subdags/subdag_paralell_dag.py took 0.035 seconds
